@startuml
'https://plantuml.com/class-diagram

interface ApocalipsisRMI
class ImplementacionApocalipsisRMI
class ApocalipsisRMIController
class Paso
class ServidorRMI
class ClienteRMI
class Apocalipsis





class Apocalipsis{
-zonas : Zona[]
-listaHumanos : ListaHilosHumano[]
-zonasTxtField : TextField[]
-cantComida = 0 : int
-HumanosComida : TextField
-comidaLock : Lock
-comidaDisponible : Condition
-listaZombies : ListaHilosZombie[]
-zombiesTxtField : TextField[]
-tuneles : Tunel[]
-apocalipsisLogs : ApocalipsisLogs
-paso : Paso

+Apocalipsis(zonasTxtField : TextField[], humanosComida : TextField, zombiesTxtField : TextField[])
+getListaHumanosEnZona(zona : int) : ListaHilosHumano
+getListaZombies() : ListaHilosZombie[]
+getZonas(zona : int) : Zona
+getTunel(idTunel : int) : Tunel
+getPaso() : Paso
+empiezaZonaComun(zona : Zona, h : Humano)
+moverHumano(zonaDestino : Zona, h : Humano)
+cogerComida(h : Humano)
+dejarComida(h : Humano, comida : int)
+imprimirComida()
+moverZonaZombie(z : Zombie, zona : int)
+defenderse(humano : Humano, zombie : Zombie)
-obtenerHumano(listaZona : ListaHilosHumano) : Humano
+comprobarParaAtacar(zombie : Zombie, zona : Zona)
+renacerComoZombie(h : Humano, zona : Zona)
}



@enduml